"""initial

Revision ID: c2d3c2c343d2
Revises: 
Create Date: 2026-06-25 23:55:18.214690

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c2d3c2c343d2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('poster_url', sa.Text(), nullable=False),
    sa.Column('telegram_file_id', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movies_category'), 'movies', ['category'], unique=False)
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('selected_tariff', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_table('payment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tariff', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proof_file_id', sa.Text(), nullable=True),
    sa.Column('external_charge_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_requests_status'), 'payment_requests', ['status'], unique=False)
    op.create_index(op.f('ix_payment_requests_user_id'), 'payment_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_requests_user_id'), table_name='payment_requests')
    op.drop_index(op.f('ix_payment_requests_status'), table_name='payment_requests')
    op.drop_table('payment_requests')
    op.drop_table('users')
    op.drop_index(op.f('ix_movies_category'), table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
